In [2]:
import torch 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__);

ModuleNotFoundError: No module named 'pandas'

# Introduction to Tensors

## Creating tensors

PyTorch tensors are creating using ```torch.Tensor()``` = https://pytorch.org/docs/stable/tensors.html


In [ ]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim ##number dimension

0

In [ ]:
# Get tensor back as Python int
scalar.item()


7

In [ ]:
# Vector 
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# MATRIX

MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[1]

tensor([ 9, 10])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

### Random tensors 

Why random tensors? 
Random tensors are important because they way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data. 

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

Torch random tensors - https://pytorch.org/docs/stable/generated/torch.rand.html

In [8]:
# Create a random tensor of size (3,4);

random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.6030, 0.7450, 0.7442, 0.8616],
        [0.4210, 0.5268, 0.3188, 0.5317],
        [0.0798, 0.6210, 0.8153, 0.9659]])

In [17]:
random_tensor.ndim

2

In [18]:
# Create a random tensor with similar shap to an image tensor 
random_image_size_tensor = torch.rand(size=(224,224,3)) # height, width, colour channel(R, G, B)
random_image_size_tensor.shape , random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

## Zeros and ones 

In [9]:
# Create a tensor of all zeros 
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [10]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [12]:
# Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [13]:

ones.dtype

torch.float32

In [16]:
random_tensor.dtype

torch.float32

### Create a range of tensors and tensors-like 

In [25]:
# Use torch.range() and get deprecated message, use torch.arange()
one_to_ten = torch.arange(1,11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
# Creating tensors like
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes
**Note:*** Tensor datatype is ones of the 3 big errors with PyTorch & deep learning: 
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [28]:
# Float 32 tensor 
float_32_tensor = torch.tensor([3.0,6.0,9.0], 
                               dtype=None, # what datatype is th tensor(3g. float32 float 16)
                               device="cpu", # What device is your tensor on 
                               requires_grad=False) # whether or not to rack gradients ith this tensor operations
float_32_tensor

tensor([3., 6., 9.])

In [29]:
float_32_tensor.dtype

torch.float32

In [31]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [32]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors (tensor attributes)

1. Tenssors not right datatype - to do get datatype from a tensor can use `tensor.dtype`
2. Tensor not right shape - to get shape form a tensor, can use `tensor.device`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`

In [33]:
# Create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.1929, 0.1618, 0.3064, 0.6261],
        [0.8329, 0.7337, 0.2421, 0.7133],
        [0.7062, 0.7504, 0.3628, 0.8552]])

In [39]:
# Find out details about some tensor
print(some_tensor)
print(f"Data type of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.1929, 0.1618, 0.3064, 0.6261],
        [0.8329, 0.7337, 0.2421, 0.7133],
        [0.7062, 0.7504, 0.3628, 0.8552]])
Data type of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu



### Manipulating Tensors (tensor operations)

