In [32]:
import torch 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__);

ModuleNotFoundError: No module named 'pandas'

# Introduction to Tensors

## Creating tensors

PyTorch tensors are creating using ```torch.Tensor()``` = https://pytorch.org/docs/stable/tensors.html


In [ ]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim ##number dimension

0

In [ ]:
# Get tensor back as Python int
scalar.item()


7

In [ ]:
# Vector 
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# MATRIX

MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[1]

tensor([ 9, 10])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

### Random tensors 

Why random tensors? 
Random tensors are important because they way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data. 

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

Torch random tensors - https://pytorch.org/docs/stable/generated/torch.rand.html

In [ ]:
# Create a random tensor of size (3,4);

random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.6030, 0.7450, 0.7442, 0.8616],
        [0.4210, 0.5268, 0.3188, 0.5317],
        [0.0798, 0.6210, 0.8153, 0.9659]])

In [ ]:
random_tensor.ndim

2

In [ ]:
# Create a random tensor with similar shap to an image tensor 
random_image_size_tensor = torch.rand(size=(224,224,3)) # height, width, colour channel(R, G, B)
random_image_size_tensor.shape , random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

## Zeros and ones 

In [ ]:
# Create a tensor of all zeros 
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:

ones.dtype

torch.float32

In [ ]:
random_tensor.dtype

torch.float32

### Create a range of tensors and tensors-like 

In [ ]:
# Use torch.range() and get deprecated message, use torch.arange()
one_to_ten = torch.arange(1,11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# Creating tensors like
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes
**Note:*** Tensor datatype is ones of the 3 big errors with PyTorch & deep learning: 
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [ ]:
# Float 32 tensor 
float_32_tensor = torch.tensor([3.0,6.0,9.0], 
                               dtype=None, # what datatype is th tensor(3g. float32 float 16)
                               device="cpu", # What device is your tensor on 
                               requires_grad=False) # whether or not to rack gradients ith this tensor operations
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors (tensor attributes)

1. Tenssors not right datatype - to do get datatype from a tensor can use `tensor.dtype`
2. Tensor not right shape - to get shape form a tensor, can use `tensor.device`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`

In [ ]:
# Create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.1929, 0.1618, 0.3064, 0.6261],
        [0.8329, 0.7337, 0.2421, 0.7133],
        [0.7062, 0.7504, 0.3628, 0.8552]])

In [ ]:
# Find out details about some tensor
print(some_tensor)
print(f"Data type of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.1929, 0.1618, 0.3064, 0.6261],
        [0.8329, 0.7337, 0.2421, 0.7133],
        [0.7062, 0.7504, 0.3628, 0.8552]])
Data type of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu



### Manipulating Tensors (tensor operations)

Tensor operations include: 
* Addition
* Subtraction 
* Multiplication (element-wise)
* Division 
* Matrix Multiplication

In [ ]:
# Create a tensor  and add 10 to it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([101, 102, 103])

In [ ]:
# Multiply tensor by 10

tensor * 10

tensor([10, 20, 30])

In [ ]:
# Subtract 10 
tensor -10


tensor([-9, -8, -7])

In [ ]:
# Try out PyTorch in-built functions
torch.mul(tensor,10)

tensor([10, 20, 30])

In [ ]:
torch.add(tensor,10)

tensor([11, 12, 13])

### Matrix multiplication

Two main ways of performing mutliplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication (dot product)

There are two main rules that perfoming matrix multiplication needs to satisfy:
1. Tne **inner dimesnsions** must match:
* `(3,2) @ (3,2)` won't work
* ` (2,3) @ (3,2)` will 

2. The resulting matrix has the shape of the **outer dimensions**: 
* `(2,3) @ (3,2)` -> `(2,2)`
* `(3,2) @ (2,3)` -> `(3,3)`

In [ ]:
m1 = torch.tensor(([3,4,2]))
m2 = torch.tensor(([[13,9,7,15],[8,7, 4,6],[6,4,0,3]]))
torch.matmul(m1,m2)

tensor([83, 63, 37, 75])

In [ ]:
# Element wise multiplication
tensor * tensor 

tensor([1, 4, 9])

In [ ]:
# Matrix multiplication 
torch.matmul(tensor,tensor)

tensor(14)

### One of the most comon errors in Machine learning: Shape Errors

In [ ]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1,2,],
                         [3,4],
                         [5,6]])
tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])
torch.matmul(tensor_A,tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using transpose 
A **transpose** switches the axes or dimensions of a given tensor

In [ ]:
tensor_B.T, tensor_B

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]))

In [ ]:
torch.mm(tensor_A,tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

## Finding the min, max, mean, sum etc ( tensor aggregation)

In [ ]:
# Create a tensor 

x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
# Find min 
torch.min(x) , x.min()

(tensor(0), tensor(0))

In [ ]:
# Find max 
torch.max(x), x.max()

(tensor(90), tensor(90))

In [35]:
# Find mean - note: the torch.mean() function requires a tensor of float32 datatype to work 
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [38]:
# Find the sum 
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [44]:
## Finding the positional min and max
x.argmin()

tensor(0)

In [45]:
## Find the positional max
x.argmax()

tensor(9)

## Reshaping, stacking ,squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shpae but keep the same memory 
* Stacking - combine multiple tensors on top of each other (vstack) or side-by-side(hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted(swapped) in a certain way


In [46]:
import torch
x = torch.arange(1,10)
x, x.shape


(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [64]:
# Add an extra dimension

x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.T

(tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]]),
 tensor([[5],
         [2],
         [3],
         [4],
         [5],
         [6],
         [7],
         [8],
         [9]]))

In [53]:
# Change the view

z = x.view(1,9)
z, z.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [54]:
# Changing z changes x ( becauase a view shares the same memory as the original)
z[:,0] = 5; 
z,x

(tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]]), tensor([5, 2, 3, 4, 5, 6, 7, 8, 9]))

In [61]:
# Stack tensor on top of each other 

x_stacked = torch.stack([x,x,x,x], dim=0)
x_stacked


tensor([[5, 5, 5, 5],
        [2, 2, 2, 2],
        [3, 3, 3, 3],
        [4, 4, 4, 4],
        [5, 5, 5, 5],
        [6, 6, 6, 6],
        [7, 7, 7, 7],
        [8, 8, 8, 8],
        [9, 9, 9, 9]])

In [67]:
#Squeeze -> removes all single dimesnsion from a target tensor

x_reshaped.shape
x_reshaped.squeeze()
x_squeezed = x_reshaped.squeeze()
x_squeezed

tensor([5, 2, 3, 4, 5, 6, 7, 8, 9])

In [69]:
#torch.unsqueeze() -adds a single dimension to a target tensor at a specific dim(dimension)

print(f"Previous target:{x_stacked}")
print(f"Previous shape:{x_squeezed.shape}")

# Add an extra dimension with unsqueeze
x_unsqueeze = x_squeezed.unsqueeze(dim=0)
print(f"New Tensor: {x_unsqueeze}")
print(f"New shape: {x_unsqueeze.shape}")

Previous target:tensor([[5, 5, 5, 5],
        [2, 2, 2, 2],
        [3, 3, 3, 3],
        [4, 4, 4, 4],
        [5, 5, 5, 5],
        [6, 6, 6, 6],
        [7, 7, 7, 7],
        [8, 8, 8, 8],
        [9, 9, 9, 9]])
Previous shape:torch.Size([9])
New Tensor: tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]])
New shape: torch.Size([1, 9])


In [72]:
#torch.permute - rearranges the dimensions of a target tensor in a specified order
x_originial = torch.rand(size=(224,224,3)) # [height, width, colour_channels]

# Permute the original tensor to rearrange the axis (or dim) order
x_permute = x_originial.permute(2,0,1)
print(f"Previous shape:{x_originial.shape}")
print(f"Permuted shape: {x_permute.shape}")

Previous shape:torch.Size([224, 224, 3])
Permuted shape: torch.Size([3, 224, 224])


## Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with NumPy.

In [82]:
# Create a tensor 
import torch 
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [83]:
# Lets index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [84]:
# Let's index on the middle bracket(dim=1)
x[0][0]

tensor([1, 2, 3])

In [89]:
# Let's index on the most inner bracket(last dimension)
x[0][0][0]

tensor(1)

In [96]:
x[0][2][2]

tensor(9)

In [99]:
# You can also use ":" to select "all" of the target dimension
x[:,0]

tensor([[1, 2, 3]])

In [100]:
# Get all values of the 0th and 1st dimension but only index 1 of 2nd dimension
x[:,:,1]

tensor([[2, 5, 8]])

In [101]:
# Get all values of the 0 dimension but only the 1 index values of 1st and 2nd dimension
x[:,1,1]

tensor([5])

In [103]:
# Get index 0 of the 0th and 1st dimension and all values of 2nd dimension
x[0,0,:]


tensor([1, 2, 3])

In [105]:
x[0,2,2]
x[0,:,2]

tensor([3, 6, 9])

## PyTorch tensors and NumPy

Numpy is a populat scientific Python numerical computing library

And becuase of ths, PyTorch has funcitonality to interact with it.

* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy `torch.Tensor.numpy()`

In [106]:
import torch 
import numpy as np

array = np.arange(1.0,8.0);
tensor = torch.from_numpy(array) # warning: when converting from numpy -> pytorch, pytrohpch refluect  numpys default datatype of float 64 unles specided otherwise 
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [107]:
array.dtype

dtype('float64')

In [108]:
# Change the value of array, what will this do to `tensor`?

array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [110]:
# Tensor to NumPy array 
tensor = torch.ones(7); 
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [111]:
# Change the tensor, what hapens to `numpy_tensor`

tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take the random out of random)

In short how a neural network learns: 
`start with random numbers -> tensor operations -> update random numbers to try and make them better representation of the data -> again -> again -> again ...`

To reduce the randomness in neural networks and PyTorch comes the concept of a 
**random seed**
Essentially what the random seed does is "flavour" the randomnes. 


In [117]:
import torch

# Create two random tensors
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)
print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.1731, 0.2299, 0.7484, 0.2714],
        [0.7515, 0.4505, 0.3046, 0.7305],
        [0.5834, 0.2332, 0.5059, 0.1444]])
tensor([[0.5653, 0.2457, 0.1622, 0.2204],
        [0.3029, 0.5330, 0.7060, 0.3908],
        [0.3881, 0.6523, 0.4476, 0.0951]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [121]:
# Let's make some random but reproducible tensors

import torch

# Set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and PyTorch objects on the GPUs (and making fast computations)

GPus = faster compution on numbers, thanks to CUDA + NVIDIA hardware + PyTorch working behind the scenes

In [124]:
### 2. check for GPU acces with PyTorch
import torch 
torch.cuda.is_available()

False

In [126]:
# Setup device agnostic code
## Run on GPU if available else use CPU
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [128]:
# Count number of devices
torch.cuda.device_count()

0

In [129]:
# 3. Putting tensors (and models on the GPU
# The reason we want out tensors/models on the GPU because GPU is faster than CPU


# Create a tensor (default on the CPU)
tensor = torch.tensor([1,2,3])
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [130]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3])

In [131]:
### 4. Moving tensors back to the CPU

# If tenso is on GPU, can't transform it to NumPy
tensor_on_gpu.numpy()

array([1, 2, 3])

In [132]:
# To fix the GPu tensor with NumPy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()

Extra-Curricular